version: 0.2

env:
  parameter-store:
      DOCKER_REGISTRY_USERNAME: /sampleapp/docker-credentials/username	
      DOCKER_REGISTRY_PASSWORD: /sampleapp/docker-credentials/password
      DOCKER_REGISTRY_URL: /sampleapp/docker-registry/url
     
phases:
  install:
    runtime-versions:
      python: 3.11
  
  
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt 
    
  build:
    commands:
      - echo "Building docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/DOCKER_REGISTRY_USERNAME/" .
      - docker push "$DOCKER_REGISTRY_URL/DOCKER_REGISTRY_USERNAME/"
      
  post_build:
    commands:
       - echo "Build is successful"
      
